
const SUPABASE_URL='https://kywxggukoqalzhuykhmx.supabase.co';
const SUPABASE_KEY='sb_publishable_ZrC415NRTShLSkSEuRAgLA_FF-57qBd';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const NAV=[['dashboard','⌘','Главная'],['plan','◈','Контент‑план'],['production','◌','Производство'],['publishing','↗','Публикации'],['integrations','⚙','Интеграции']];
const STATUS={draft:'Черновик',production:'В работе',review:'Согласование',approved:'Одобрено',scheduled:'Запланировано',published:'Опубликовано',failed:'Ошибка'};
let state={session:null,clients:[],clientId:null,content:[],integrations:[],view:'dashboard'};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function toast(msg,err=false){const t=$('toast');t.textContent=msg;t.className='toast on'+(err?' err':'');setTimeout(()=>t.className='toast',4200)}
function nav(){ $('menu').innerHTML=NAV.map(x=>`<button class="nav ${x[0]===state.view?'on':''}" data-v="${x[0]}">${x[1]} <span>${x[2]}</span></button>`).join(''); document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.v)); }
function show(v){state.view=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id===v));$('title').textContent=NAV.find(x=>x[0]===v)[2];$('crumb').textContent='Контент‑центр · '+(currentClient()?.name||'');nav()}
function currentClient(){return state.clients.find(x=>x.id===state.clientId)}
function fmtDate(v){if(!v)return '—';return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
async function boot(){const s=await sb.auth.getSession();state.session=s.data.session;if(!state.session){$('authLayer').classList.add('on');return}$('authLayer').classList.remove('on');await loadClients()}
async function claim(){const code=$('setupCode').value.trim();if(!code)return toast('Введите setup‑код',true);$('claimBtn').disabled=true;try{const r=await fetch(SUPABASE_URL+'/functions/v1/claim-owner-v2',{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({code})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Ошибка активации');const verified=await sb.auth.verifyOtp({token_hash:b.token_hash,type:'magiclink'});if(verified.error)throw verified.error;state.session=verified.data.session;$('authLayer').classList.remove('on');toast('Кабинет активирован');await loadClients()}catch(e){toast(e.message,true)}finally{$('claimBtn').disabled=false}}

async function loadClients(){const q=await sb.from('clients').select('*').order('name');if(q.error)return toast(q.error.message,true);state.clients=q.data||[];if(!state.clients.length)return toast('Нет доступных клиентов',true);if(!state.clientId)state.clientId=state.clients[0].id;$('client').innerHTML=state.clients.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.business_type||'')}</option>`).join('');$('client').value=state.clientId;await loadClientData();nav();show(state.view)}
async function loadClientData(){const [c,i]=await Promise.all([sb.from('content_items').select('*').eq('client_id',state.clientId).order('scheduled_at',{ascending:true,nullsFirst:false}),sb.from('client_integrations').select('*').eq('client_id',state.clientId).order('channel')]);if(c.error)return toast(c.error.message,true);if(i.error)return toast(i.error.message,true);state.content=c.data||[];state.integrations=i.data||[];renderAll()}
function renderAll(){renderDash();renderPlan();renderProd();renderPublishing();renderIntegrations();$('crumb').textContent='Контент‑центр · '+(currentClient()?.name||'')}
function renderDash(){const c=currentClient(),a=state.content,approved=a.filter(x=>x.status==='approved').length,work=a.filter(x=>['draft','production','review'].includes(x.status)).length,pub=a.filter(x=>x.status==='published').length;const progress=Math.min(95,Math.max(20,Math.round((pub+approved)/(Math.max(1,a.length))*100)));const stage=work?'Контент и производство':approved?'Готово к публикации':'Планирование';$('dashboard').innerHTML=`<div class="hero"><div class="card"><div class="head"><div><div class="lab">Текущий этап</div><div class="stage">${esc(stage)}</div></div><span class="badge">${progress}% цикла</span></div><div class="sub">${esc(c?.name)} · контент, материалы и публикации изолированы от других клиентов.</div><div class="bar"><i style="width:${progress}%"></i></div></div><div class="metrics"><div class="metric"><b>${a.length}</b><small>материалов</small></div><div class="metric"><b>${approved}</b><small>готово</small></div><div class="metric"><b>${work}</b><small>в работе</small></div></div></div><div class="grid"><div class="card"><div class="lab">Ближайший контент</div>${a.slice(0,5).map(x=>rowHtml(x)).join('')||'<div class="empty">Материалов пока нет</div>'}</div><div class="card"><div class="lab">Бренд‑правила</div><div class="stage" style="font-size:18px">${esc(c?.business_type||'Клиент')}</div><pre class="sub" style="white-space:pre-wrap">${esc(JSON.stringify(c?.brand_rules||{},null,2))}</pre></div><div class="card"><div class="lab">ChatGPT</div><div class="stage" style="font-size:18px">Контекст клиента</div><p class="sub">Скопируйте актуальный набор данных в ChatGPT без смешивания проектов.</p><button class="ghost" onclick="copyGPT()">Скопировать GPT‑контекст</button></div></div>`}
function rowHtml(x){return `<div class="row"><div><div class="rt">${esc(x.title)}</div><div class="rs">${fmtDate(x.scheduled_at)} · ${esc(x.format)} · ${esc(x.channel)}</div></div><span class="status ${x.status}">${STATUS[x.status]||x.status}</span></div>`}
function renderPlan(){$('plan').innerHTML=`<div class="section"><div><h2>Контент‑план · ${esc(currentClient()?.name)}</h2><p>Дата, формат, канал и статус сохраняются в Supabase.</p></div></div><div class="card tw"><table class="table"><tr><th>Дата</th><th>Материал</th><th>Формат</th><th>Канал</th><th>Статус</th><th>Media</th></tr>${state.content.map(x=>`<tr><td>${fmtDate(x.scheduled_at)}</td><td><b>${esc(x.title)}</b></td><td>${esc(x.format)}</td><td>${esc(x.channel)}</td><td><select class="mini-select" onchange="changeStatus('${x.id}',this.value)">${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${k===x.status?'selected':''}>${v}</option>`).join('')}</select></td><td>${Array.isArray(x.media_urls)?x.media_urls.length:0}</td></tr>`).join('')}</table></div>`}
function renderProd(){const cols=[['draft','Черновики'],['production','В работе'],['review','Согласование'],['approved','Готово']];$('production').innerHTML=`<div class="section"><div><h2>Производство · ${esc(currentClient()?.name)}</h2><p>Канбан контентного цикла.</p></div></div><div class="kanban">${cols.map(([s,n])=>`<div class="lane"><h3>${n}</h3>${state.content.filter(x=>x.status===s).map(x=>`<div class="task"><b>${esc(x.title)}</b><p>${esc(x.format)} · ${esc(x.channel)}</p><span class="sub">${fmtDate(x.scheduled_at)}</span></div>`).join('')||'<div class="empty">Пусто</div>'}</div>`).join('')}</div>`}
function renderPublishing(){const list=state.content.filter(x=>['approved','scheduled','failed','published'].includes(x.status));$('publishing').innerHTML=`<div class="section"><div><h2>Публикации · ${esc(currentClient()?.name)}</h2><p>Прямая отправка идёт через Supabase Edge Function → Composio → соцсеть.</p></div></div><div class="card">${list.map(x=>`<div class="row"><div><div class="rt"><b>${esc(x.title)}</b></div><div class="rs">${esc(x.channel)} · ${esc(x.format)} · media: ${Array.isArray(x.media_urls)?x.media_urls.length:0}</div></div><div style="display:flex;gap:8px;align-items:center"><span class="status ${x.status}">${STATUS[x.status]||x.status}</span>${['approved','scheduled','failed'].includes(x.status)?`<button class="publish-btn" onclick="publishItem('${x.id}')">Опубликовать</button>`:''}</div></div>`).join('')||'<div class="empty">Нет материалов для публикации</div>'}</div>`}
function renderIntegrations(){const by=ch=>state.integrations.find(x=>x.channel===ch);const ig=by('Instagram'),tg=by('Telegram');$('integrations').innerHTML=`<div class="section"><div><h2>Интеграции · ${esc(currentClient()?.name)}</h2><p>Каждый клиент имеет собственные connection IDs и target‑настройки.</p></div></div><div class="ints"><div class="int"><div style="display:flex;gap:11px;align-items:center"><div class="logo">IG</div><div><b>Instagram</b><div class="rs">${esc(ig?.metadata?.username||'не указан')}</div></div></div><span class="${ig?.enabled?'ok':'need'}">${ig?.enabled?'● подключено':'● нужно подключить'}</span></div><div class="int"><div style="display:flex;gap:11px;align-items:center"><div class="logo">TG</div><div><b>Telegram</b><div class="rs">Bot + channel</div></div></div><span class="${tg?.enabled?'ok':'need'}">${tg?.enabled?'● бот подключён':'● нужно подключить'}</span></div></div><div class="card" style="margin-top:12px"><div class="lab">Telegram target</div><p class="sub">Укажите @channelusername или числовой chat_id. Telegram не вернул updates, поэтому автоматически определить канал пока невозможно.</p><div class="cols"><input class="input" id="tgTarget" value="${esc(tg?.external_target||'')}" placeholder="@channelusername или -100..."><button class="primary" onclick="saveTelegramTarget()">Сохранить</button></div></div><div class="card" style="margin-top:12px"><div class="lab">Composio server secret</div><div class="warning">Для прямой кнопки «Опубликовать» серверу нужен secret <b>COMPOSIO_API_KEY</b> в Supabase Edge Function Secrets. Ключ не должен попадать в этот HTML.</div></div>${!ig?.enabled||!tg?.enabled?`<div class="card" style="margin-top:12px"><div class="lab">Подключение новых аккаунтов</div><p class="sub">Новые соцсети подключаются через ChatGPT + Composio, затем их connection ID сохраняется здесь отдельно для клиента.</p><button class="ghost" onclick="copyConnectCommand()">Скопировать команду для ChatGPT</button></div>`:''}`}
async function changeStatus(id,status){const r=await sb.from('content_items').update({status}).eq('id',id);if(r.error)return toast(r.error.message,true);toast('Статус сохранён');await loadClientData()}
async function saveTelegramTarget(){const tg=state.integrations.find(x=>x.channel==='Telegram');if(!tg)return toast('Telegram интеграция не создана',true);const target=$('tgTarget').value.trim();const r=await sb.from('client_integrations').update({external_target:target}).eq('id',tg.id);if(r.error)return toast(r.error.message,true);toast('Telegram target сохранён');await loadClientData()}
async function publishItem(id){if(!confirm('Опубликовать этот материал сейчас?'))return;toast('Отправляю в публикацию…');try{const s=(await sb.auth.getSession()).data.session;const r=await fetch(SUPABASE_URL+'/functions/v1/publish-content',{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':'Bearer '+s.access_token},body:JSON.stringify({content_item_id:id})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Ошибка публикации');toast('Опубликовано');await loadClientData()}catch(e){toast(e.message,true);await loadClientData()}}
async function addContent(){const title=$('fTitle').value.trim();if(!title)return toast('Введите название',true);const media=$('fMedia').value.split('\n').map(x=>x.trim()).filter(Boolean);const scheduled=$('fDate').value?new Date($('fDate').value).toISOString():null;const r=await sb.from('content_items').insert({client_id:state.clientId,title,format:$('fFormat').value,channel:$('fChannel').value,status:$('fStatus').value,scheduled_at:scheduled,caption:$('fCaption').value.trim(),media_urls:media});if(r.error)return toast(r.error.message,true);$('contentModal').classList.remove('on');['fTitle','fDate','fCaption','fMedia'].forEach(id=>$(id).value='');toast('Материал добавлен');await loadClientData()}
function copyGPT(){const payload={client:currentClient(),content:state.content,integrations:state.integrations.map(x=>({channel:x.channel,enabled:x.enabled,external_account_id:x.external_account_id,external_target:x.external_target,metadata:x.metadata}))};navigator.clipboard.writeText('Работаем только с клиентом '+currentClient().name+'. Не смешивай данные других клиентов. Контекст: '+JSON.stringify(payload)).then(()=>toast('GPT‑контекст скопирован'))}
function copyConnectCommand(){navigator.clipboard.writeText('Подключи в Composio отдельные Instagram и Telegram аккаунты для клиента '+currentClient().name+' и после подключения сохрани их connection IDs в Content Center. Не используй аккаунты других клиентов.').then(()=>toast('Команда скопирована'))}
$('claimBtn').onclick=claim;$('client').onchange=async e=>{state.clientId=e.target.value;await loadClientData();show(state.view)};$('addBtn').onclick=()=> $('contentModal').classList.add('on');$('cancelAdd').onclick=()=> $('contentModal').classList.remove('on');$('saveAdd').onclick=addContent;$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
boot();
